apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: fastboop-web
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastboop-web
  updatePolicy:
    updateMode: Auto
