apiVersion: v1
kind: Secret
metadata:
    name: conduit-recovery
    namespace: fastboop
type: Opaque
stringData:
    emergency-password: ENC[AES256_GCM,data:nRhkZPrxE6ZnL0qmaEe/wpNbBm7lu2QDJb8nwLKPzrQLPdVd5i3YRpZ/FQrGr+3FA2ZbHeP18DnmqR4Zme8wXA==,iv:+sezx+3Z9XR/1NpJ0NZUDzswx3BG28vPiqTWKZi2POo=,tag:iMpmzyEv4rHI5Y7LdmWI3w==,type:str]
sops:
    age:
        - recipient: age14708z8r3upms53n3akgywym8wdlu0r7m5tq52g9cjqmsgf7t7u5qlpmqg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueVIrNEhpR0JpSzF0UjlC
            ZUYyMGU2WTQ1bEV2UmZzS3lLdHVobVBzVlRFCmF4c1V2RjdoemRVL3ZpNkdVdUw1
            OUVNZnRYalg2dGoxUUlVdFRPOE5HbUkKLS0tIHBMTHU4QVdFNFI0RVpBb0JvSDJs
            YjZsd3BYajVRb2crUWx3cUprejFySm8KwySpLYfwYKdgCOXQtJ0QyzgIqPW2LeZ6
            povPWfiCcygHp5yOQT+337D4FCvljzVKlMp0q2gs4zTo6KMLK0fUFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T09:07:25Z"
    mac: ENC[AES256_GCM,data:GzKVHyR3CbCLcvmlJYS2Znic5zEsFudPCkQcRYcCXyGhvyDZ7n8FHUz2YPk5odoCAUr0UMe80fJeCOMWvhcN2YaFbqucLSAE4SDIOTkCYt2Ril9oU0L4LzzVtu/4rty6q53pIgP6CM0CivM8ffEuilJI76YfoB4a1IAog0aLQBE=,iv:oaEdwdMbfCuXd75I5WKb6iVP8G6BfG9wZdEHioQywow=,tag:7M/oKm+B8JiNI5q4bILujA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
