apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fastboop
resources:
  - repositories.yaml
  - fastboop-web
  - frontdoor
  - frontdoor-edge
  - image-automation
  - conduit
  - gha-proxy
configMapGenerator:
  - name: live-version
    files:
      - LIVE_VERSION=live-version.txt
