[Distribution]
Distribution=fedora
Architecture=arm64

[Output]
Format=directory
Output=fastboop-example-rootfs
OutputDirectory=../assets/rootfs
SplitArtifacts=

[Content]
Packages=
        busybox
        kernel-core
        kernel-modules
        kernel-modules-core
        systemd
WithDocs=no
WithRecommends=no
Bootable=no
RemoveFiles=
        /var/cache/*
        /var/log/*
