apiVersion: v1
kind: Secret
metadata:
    name: gha-proxy
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:F8tVY/ViAgwn9ubHupWwbmW2htH8L1dWNCdlGImDs2im9Raj/ptSorhpS0FOFfrIp41nLp0HQwwtci0+dVJ9nu1pD6r0mvL5bGGKXI0OPizdqSkaIU9UtwbI32Q3,iv:jm1HHEVunvOozITXQplcM97yoKhKZGB01BrLTgqiciM=,tag:oISV857O/wodbNlJOR5NTA==,type:str]
sops:
    age:
        - recipient: age14708z8r3upms53n3akgywym8wdlu0r7m5tq52g9cjqmsgf7t7u5qlpmqg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeWYwbHlndlIvMFJ2eTlG
            M2lWM0lUcTFjNzlHRW9YMGhYbStLYllUb25vCkRuYlpRSS9DREZQZmYzV0NURGZY
            TU5maVoxR2k2S29oZHQvT3U5eVdtSnMKLS0tIFdFT1RhVGRmSGlmRGJJVVdVT3Fn
            cWNWRkE2bm16VnBYYkpEZExoazBGQ28KJFYj9TaZrd4Xq8enKy9U/Fz1k5T7kO/z
            8nxVkZZFmcIuPPar0XznSX/gI6jj95Mguc98mMHP9V4EwJa+7aZRlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T07:26:53Z"
    mac: ENC[AES256_GCM,data:GV5EJRymuozlj4fC9cuYfbBgoGAEZRWKuR1js8aTsi6tv+T57a1oUmWq8NtuYwvUSOIcPxMuw8hWVvvXDyWCz95cMmqHQh6cNQGu2a72JnTMNmKpNGgFiL0htz1sOw4XAwaG4BkdgbnEfrPsEzz8zn6fSNC1pXQ88K+MtytVHEo=,iv:JhG/h8idXw+oJHc415oB5w/JhLq6k6Ut0f62OzxwfE4=,tag:88fCtLsVyqIAluutfrLYVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
